# Site settings
title: "Servo Blog"
description: ""
url: "https://blog.servo.org"
baseurl: ""
google_analytics: 

#  Build settings
permalink: pretty
paginate: 10

twitter:
  username: ServoDev

gems:
  - jekyll-redirect-from
  - jekyll-seo-tag
